-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 19:54:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AbpBase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AbpBase` ;

-- -----------------------------------------------------
-- Schema AbpBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AbpBase` DEFAULT CHARACTER SET utf8 ;
USE `AbpBase` ;

-- -----------------------------------------------------
-- Table `AbpBase`.`Pista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Pista` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Pista` (
  `idPista` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Disponibilidad` TINYINT NOT NULL,
  PRIMARY KEY (`idPista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Usuario` (
  `Dni` VARCHAR(12) NOT NULL,
  `Login` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(25) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(6) CHARACTER SET 'armscii8' NOT NULL,
  `Tipo` VARCHAR(12) NOT NULL,
  `Telefono` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`Dni`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Usuario_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Usuario_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Usuario_has_Usuario` (
  `Usuario_Dni` VARCHAR(12) NOT NULL,
  `Usuario_Dni1` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Usuario_Dni`, `Usuario_Dni1`),
  INDEX `fk_Usuario_has_Usuario_Usuario1_idx` (`Usuario_Dni1` ASC) ,
  INDEX `fk_Usuario_has_Usuario_Usuario_idx` (`Usuario_Dni` ASC) ,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `AbpBase`.`Usuario` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Dni1`)
    REFERENCES `AbpBase`.`Usuario` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Reserva` (
  `Usuario_Dni` VARCHAR(12) NOT NULL,
  `Pista_idPista` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  `Hora` TIME NOT NULL,
  PRIMARY KEY (`Usuario_Dni`, `Pista_idPista`),
  INDEX `fk_Usuario_has_Pista_Pista1_idx` (`Pista_idPista` ASC) ,
  INDEX `fk_Usuario_has_Pista_Usuario1_idx` (`Usuario_Dni` ASC) ,
  CONSTRAINT `fk_Usuario_has_Pista_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `AbpBase`.`Usuario` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pista_Pista1`
    FOREIGN KEY (`Pista_idPista`)
    REFERENCES `AbpBase`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Campeonato` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Campeonato` (
  `IdCampeonato` INT NOT NULL,
  `FechaIni` DATETIME NOT NULL,
  `FechaFin` DATETIME NOT NULL,
  PRIMARY KEY (`IdCampeonato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Categoría`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Categoría` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Categoría` (
  `IdCampeonato` INT NOT NULL,
  `Tipo` VARCHAR(9) NOT NULL,
  `Nivel` INT NOT NULL,
  PRIMARY KEY (`IdCampeonato`, `Tipo`, `Nivel`),
  CONSTRAINT `fk_cat_campeonato`
    FOREIGN KEY (`IdCampeonato`)
    REFERENCES `AbpBase`.`Campeonato` (`IdCampeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Pareja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Pareja` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Pareja` (
  `idCampeonato` INT NOT NULL,
  `Tipo` VARCHAR(9) NOT NULL,
  `Nivel` INT NOT NULL,
  `NumPareja` INT NOT NULL,
  `Capitan` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idCampeonato`, `Tipo`, `Nivel`, `NumPareja`),
  CONSTRAINT `fk_par_cat`
    FOREIGN KEY (`idCampeonato` , `Tipo` , `Nivel`)
    REFERENCES `AbpBase`.`Categoría` (`IdCampeonato` , `Tipo` , `Nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Grupo` (
  `IdCampeonato` INT NOT NULL,
  `Tipo` VARCHAR(9) NOT NULL,
  `Nivel` INT NOT NULL,
  `Letra` CHAR NOT NULL,
  PRIMARY KEY (`IdCampeonato`, `Tipo`, `Nivel`, `Letra`),
  CONSTRAINT `fk_cat_grupo`
    FOREIGN KEY (`IdCampeonato` , `Tipo` , `Nivel`)
    REFERENCES `AbpBase`.`Categoría` (`IdCampeonato` , `Tipo` , `Nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Partido` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Partido` (
  `IdCampeonato` INT NOT NULL,
  `Tipo` VARCHAR(8) NOT NULL,
  `Nivel` INT NOT NULL,
  `Grupo_Letra` CHAR NOT NULL,
  `NumEnfrentamiento` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`IdCampeonato`, `Tipo`, `Nivel`, `Grupo_Letra`, `NumEnfrentamiento`),
  CONSTRAINT `fk_partido_grupo`
    FOREIGN KEY (`IdCampeonato` , `Tipo` , `Nivel` , `Grupo_Letra`)
    REFERENCES `AbpBase`.`Grupo` (`IdCampeonato` , `Tipo` , `Nivel` , `Letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Promociones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Promociones` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Promociones` (
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  PRIMARY KEY (`Fecha`, `Hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`IncripcionPromociones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`IncripcionPromociones` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`IncripcionPromociones` (
  `Usuario_Dni` VARCHAR(12) NOT NULL,
  `Promociones_Fecha` DATE NOT NULL,
  `Promociones_Hora` TIME NOT NULL,
  PRIMARY KEY (`Usuario_Dni`, `Promociones_Fecha`, `Promociones_Hora`),
  INDEX `fk_Usuario_has_Promociones_Promociones1_idx` (`Promociones_Fecha` ASC, `Promociones_Hora` ASC),
  INDEX `fk_Usuario_has_Promociones_Usuario1_idx` (`Usuario_Dni` ASC) ,
  CONSTRAINT `fk_Usuario_has_Promociones_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `AbpBase`.`Usuario` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Promociones_Promociones1`
    FOREIGN KEY (`Promociones_Fecha` , `Promociones_Hora`)
    REFERENCES `AbpBase`.`Promociones` (`Fecha` , `Hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`UsuarioParejas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`UsuarioParejas` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`UsuarioParejas` (
  `Usuario_Dni` VARCHAR(12) NOT NULL,
  `Pareja_idCampeonato` INT NOT NULL,
  `Pareja_Tipo` VARCHAR(9) NOT NULL,
  `Pareja_Nivel` INT NOT NULL,
  `Pareja_NumPareja` INT NOT NULL,
  PRIMARY KEY (`Usuario_Dni`, `Pareja_idCampeonato`, `Pareja_Tipo`, `Pareja_Nivel`, `Pareja_NumPareja`),
  INDEX `fk_Usuario_has_Pareja_Pareja1_idx` (`Pareja_idCampeonato` ASC, `Pareja_Tipo` ASC, `Pareja_Nivel` ASC, `Pareja_NumPareja` ASC),
  INDEX `fk_Usuario_has_Pareja_Usuario1_idx` (`Usuario_Dni` ASC) ,
  CONSTRAINT `fk_Usuario_has_Pareja_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `AbpBase`.`Usuario` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pareja_Pareja1`
    FOREIGN KEY (`Pareja_idCampeonato` , `Pareja_Tipo` , `Pareja_Nivel` , `Pareja_NumPareja`)
    REFERENCES `AbpBase`.`Pareja` (`idCampeonato` , `Tipo` , `Nivel` , `NumPareja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AbpBase`.`Enfrentamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Enfrentamiento` ;

CREATE TABLE IF NOT EXISTS `AbpBase`.`Enfrentamiento` (
  `IdCampeonato` INT NOT NULL,
  `Tipo` VARCHAR(9) NOT NULL,
  `Nivel` INT NOT NULL,
  `Letra` CHAR NOT NULL,
  `NumEnfrentamiento` INT NOT NULL,
  `NumPareja` INT NOT NULL,
  PRIMARY KEY (`IdCampeonato`, `Tipo`, `Nivel`, `Letra`, `NumEnfrentamiento`, `NumPareja`),
  INDEX `fk_Pareja_has_Partido_Pareja1_idx` (`IdCampeonato` ASC, `Tipo` ASC, `Nivel` ASC, `NumPareja` ASC) ,
  CONSTRAINT `fk_Pareja_has_Partido_Pareja1`
    FOREIGN KEY (`IdCampeonato` , `Tipo` , `Nivel` , `NumPareja`)
    REFERENCES `AbpBase`.`Pareja` (`idCampeonato` , `Tipo` , `Nivel` , `NumPareja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pareja_has_Partido_Partido1`
    FOREIGN KEY (`IdCampeonato` , `Tipo` , `Nivel` , `Letra` , `NumEnfrentamiento`)
    REFERENCES `AbpBase`.`Partido` (`IdCampeonato` , `Tipo` , `Nivel` , `Grupo_Letra` , `NumEnfrentamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `AbpBase` ;

-- -----------------------------------------------------
-- Placeholder table for view `AbpBase`.`Clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AbpBase`.`Clasificacion` (`IdCampeonato` INT, `Tipo` INT, `Nivel` INT, `Letra` INT, `Login` INT);

-- -----------------------------------------------------
-- View `AbpBase`.`Clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AbpBase`.`Clasificacion`;
DROP VIEW IF EXISTS `AbpBase`.`Clasificacion` ;
USE `AbpBase`;
CREATE OR REPLACE VIEW `Clasificacion` AS select E.IdCampeonato,E.Tipo,E.Nivel,E.Letra,U.Login 
from Enfrentamiento E, UsuarioParejas UP, Usuario U 
where UP.Pareja_idCampeonato = E.IdCampeonato AND UP.Pareja_Tipo=E.Tipo AND UP.Pareja_Nivel=E.Nivel AND UP.Pareja_NumPareja=E.NumPareja AND U.Dni=UP.Usuario_Dni;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
